os: linux
dist: trusty
language: bash
sudo: required
services: docker
cache: false
env:
  matrix:
    - ARCH=x86_64
    - ARCH=aarch64
    - ARCH=armv7l
    - ARCH=armhf
before_script:
- uname -a
- docker --version
- make --version
script:
  - make ARCH=${ARCH} BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} BRANCH=${TRAVIS_BRANCH} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
